### ISSUE TITLE
Mini-Contests Day 1 - Claim Rewards and Re-stake

### ISSUE THREAD

**Issue by delroybosco** [maticnetwork/matic-bounties#11]
Hey @validators,

Welcome to Day 1 of the Mini-contests. To earn rewards, you will need to perform a couple of tasks. On completing the tasks successfully, you will have to submit proof of actions taken.

The first 30 validators to do so (correctly) will win $10 worth of MATIC tokens each. The prize pool for Day 1 is $300 worth of MATIC tokens. 

Before you proceed, we have noticed that there may be some issues with accessing the Dashboard on Firefox. We suggest you to use Chrome or Brave for better accessibility.

**How to play and win**

1. First you will need to login to the Matic Staking Dashboard: [https://wallet.matic.today/staking](https://wallet.matic.today/staking).
2. Once you have logged in go to your validator profile, you will see 2 buttons in yellow - `Claim Rewards` and `Restake Rewards`.

**Claim Rewards**:

1. Click on `Claim Rewards` and you will get a confirmation to claim your rewards. You will need to confirm the transaction on Metamask.
2. Once you get a confirmation from Metamask, your rewards will be added to your account. Check the test token balances. Your rewards on the Dashboard should be zero after confirmation.
3. Take a note of the Transaction Hash of claimed rewards transaction on Goerli. It will be required later for proof submission.

For your reference:

The transaction hash on Goerli will mention how many tokens were claimed as rewards.

![Screenshot 2020-03-23 at 4 24 52 PM](https://user-images.githubusercontent.com/44167007/77313206-6a233380-6d29-11ea-8519-193ed412c8e8.png)

**Restake**: 

Note that you can either restake your rewards or restake the remaining amount of tokens that you have left. You don't need to stake a higher amount. A minimum of 10 tokens should be good.

1. Click on Restake Rewards and you will a pop-up on the screen which will look something like this

![Screenshot 2020-03-23 at 4 12 25 PM](https://user-images.githubusercontent.com/44167007/77313160-57106380-6d29-11ea-8f81-92f075706632.png)

2. Click on `Add more stake` and you will see a text box open up. You can add the number of tokens in that text box that you want to restake.

3. When you click on 'Restake' it will ask you for confirmation from Metamask. After the first confirmation, it will take you back to the Dashboard with the pop-up on the screen. **DO NOT** click on anything yet. 

4. It should automatically take you back to Metamask for the 2nd confirmation. Once both the transactions are confirmed you should see the "Total Stake" value to be increased.

5. You need to take note of the transaction hash for the 2nd confirmation transaction on Goerli.

For your reference: 

Your 2nd transaction on Goerli would contain the number of tokens you staked.

![Screenshot 2020-03-23 at 4 18 58 PM](https://user-images.githubusercontent.com/44167007/77313058-2fb99680-6d29-11ea-8f6d-86dd7da35562.png)

You can get your transaction hash from here: [https://goerli.etherscan.io/](https://goerli.etherscan.io/)

**How to submit proof?**

Format:

My Address: 0x7eD7f36694153bA6EfF6ca6726b60F6E2Bb17fcf

**Claim Reward**: 

I claimed 241 Matic Tokens and here is the proof -  [https://goerli.etherscan.io/tx/0xd3a57336679b394ae02e748ace84bb078b1ea33b8839c32cc1e28f8c61be48d1](https://goerli.etherscan.io/tx/0xd3a57336679b394ae02e748ace84bb078b1ea33b8839c32cc1e28f8c61be48d1)

**Restake**: I restaked 10 Matic Tokens and here is the proof - [https://goerli.etherscan.io/tx/0xbd264c2a2abbba322392cf86f42837389d3187fddb4770ea9a7f8e4c30dcee9b](https://goerli.etherscan.io/tx/0xbd264c2a2abbba322392cf86f42837389d3187fddb4770ea9a7f8e4c30dcee9b)

You will be disqualified if your submission is not in the correct format. Remember the first 30 validators with correct entries will be selected.

Rewards for all the winners will be distributed at the end of Stage 1.

Let the games begin!

**Comment by shaimo** [comment]
My address: 0x4d27A3b75Ff79cD70a8BA91518e35f1D1Dc1C26d

I claimed 59.964578106678410626 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe8fcc5cbb70937af6389691940ad48a537b590ac46bcf400c548a5d0f538936f

I restaked 60 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x280f1987f8dbc0b0a3bee88ecaa4dcef823b597790f76661838e38894afcc1a9

**Comment by kvdv80** [comment]
My Address: 0x78162309525D2A692F1ca2Edf764705Cb6ba8DcC

Claim Reward:

I claimed 5.433 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xa1b3f002ff2b0425fb47ed93784fe00364a0069ab0a3bca414b8de25ede07355

Restake: I restaked 6 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xb46a49b50b0cd6bbf17d7dc9331e864688ee26de2b87af8cfc05c5ba2fe11537

**Comment by kamalzaman** [comment]
My Address: 0x97546D8169AaB23e45e40f394C326fC5F874E9eb

Claim Reward:

I claimed 4.858887206515143655 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xf9f4029ee7aeeb9b06f20061f6f37ef7bee5b8a913c1cdfc995de93ce387db20

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe7868e537b2d7f94f9b35e3053239ec49ab130154239ffce40dcb88235ec9a2f

**Comment by raulillo82** [comment]
My Address: 0xc4E88c8BaaE79049841750B36e6D10401f1688F5

Claim Reward:

I claimed 22.638954236410281203 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x796b76c4d824a371d121659ff2e79346f56177bdcc07d8453603f1e6f9f6fe99

Restake: I restaked 12 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xa5806daa28071bba7bff855614d1629533f38a3810d5ab58430a7e4b910c6850
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~

**Comment by divyaN73** [comment]
My Address: 0xCeb5E3F7b79e1437cc48acadE00726E9C5dA8E3D

Claim Reward:

I claimed 2.512017550697864713 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0xc8f7f6257f1e5a033d6f4a8bf8f71004916fecb973e9ac382095abaa4ed011d8

Restake: I restaked 3 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0xa94f237d330669c00bab43c6cb7ea33c04b16f23c8e15d5dea99c5f35676bb2d

**Comment by optim1stic** [comment]
My Address: 0x67EB7C8f2d8c0Df0729F9a99795b7B2c46c2DB7B

Claim Reward:

I claimed 96.489277450402481521 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x76a19bbc3dfc84c273afd344e3bbc07eaf48a41b1fb34883695eb79797e2f01a

Restake: I restaked 20 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc57adc854baa11056ac0e91139ae90f37b698ed612f0136deb385945a95fbc8c

**Comment by snegkovka** [comment]
My Address: 0xf8d1127780b89f167cb4578935e89b8ea1de774f

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xcf3d9d02b9687b26b5a2031ad2fc4aa6f43d5f40dca35f7dd4d27d1db26e8c94

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x2b705dfb6ad15c3678830af0f804b6ad5c29ac0a45cf37369d2dfbbb8a973ec8

**Comment by virge2019** [comment]
My Address: 0x2c3fDCEf2A7Bf71bcFefb576b4c6A0De4984B225

Claim Reward:
I claimed 1.503586467141511493 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0x32308e3c731f64bbbda1b79ccfcbccb607d553bcce0eaf74aa55cf833310827a

Restake: I restaked 5.34 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0x872617a59df8a7034e715fc530e9ed73f79b3a5e3082b9c2a1d12246e2bf3a57

**Comment by latenthero** [comment]
My Address: 0xeB81a413B01e9482ddc46D0c77Ee8918bb44B30c

Claim Reward:

I claimed 81.195968 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x3ecff5b9712bec10f9dd54c677b90235fd3afda333b64f71706947be75008ebe

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7f200000a32b427e2cab0cdcf832b2dea8ea3f5b1e1c554ea16c573e08c8902f

**Comment by bajazid** [comment]
My Address: 0x732aC9DF92d9DD32A9C7aA9fCB9a76317fF1c2B6

Claim Reward:

I claimed 22.596786009992390907 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xd59e11fc64fb30d723b7c6549089403cb2557d3e1e570c13d887d493525fe48b

Restake: I restaked 13 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5af675ddfe0ab5b1730a179de6359060ed5f881b725709b1474edfeec849d657

**Comment by mr0wnage** [comment]
My Address: 0x277bC0C390917e0588B1Df7173DcbE6f0D9DA111

Claim Reward:

I claimed 5.15 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x6a33650efe455894d12bc5b36e8fc66c40de556781c12bdbdd02ae10f37303d9

Restake: I restaked 15 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x777ea30b9da92928462b65f2e773af1a81145f5fc14ac54f6fbfb0c815d7481b

**Comment by blueatsky** [comment]
My Address: 0x3F21B71F7C5f7733EBf8A9233e9D022baA3713f5

Claim Reward:

I claimed 82.59 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xf5a66f6df249a52a2207b0d322a773705089f6c0baa80d24fc723ab6143d6b64

Restake: I restaked 15 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x6af0c4a53a0050d3ca3a00e92c6685a7d3bd7035992ce45c69368ce5e26bbdda

**Comment by hk0601** [comment]
My address 0x247490413303cF21b7c86205A25DC4C3A6b74f88

Claim Reward:

I claimed 8.68 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x4e51417768cb29f4b2673bd9d58f85616ed209b11e8e5854a4a7016ba3027bdb

Restake: I restaked 80 Matic Tokens and here is the proof - 
https://goerli.etherscan.io/tx/0x1b3326dd2e27113134534915de151ebac31b36d148de62eab8d91f0ba7097f60

**Comment by Easonsc** [comment]
My Address: 0x5Be3a4B4EDC39D58cF7e3556eA9E1E271F6d8b73

Claim Reward:

I claimed 82.47 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x934c9c9a1658bd2649e5f8052b0260d5ae725be07f4e99f5c798452006fe7a62

Restake: I restaked 30 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x302cb52d430e79074bc7616a8a91a284e2cf502a0a0c9cdc121705d804a335d6

**Comment by aynelis** [comment]
My Address: 0xAbB9D8644E56cB77C8593d317D84E428357f7CC5

Claim Reward:

I claimed 28.873250090004818769 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xf2a3b8863d0dca36a1dc9bfa4da62a79cf9ee46ce37eade9d532ee9625597b49

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5314dc342fd04e7014769fd4187de15e172117dc84354ab2f98063b0dd38bb6b

**Comment by malise800** [comment]
My Address: 0x097223Ee83e714e25aF3eC698293c635Bea05796

Claim Reward:

I claimed 1.6 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe41ae326acb5c4850409389018be421437d7a5286eda800e655c6335ed4deb0a

Restake: I restaked 1.6 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xbd264c2a2abbba322392cf86f42837389d3187fddb4770ea9a7f8e4c30dcee9b

**Comment by kapecizvelet** [comment]
My Address: 0xce717b0a1ee4869fe9075838ddb59b78176b1ce9

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x1c483db30040204a78b30a4ec270b461720bb68b384af83f1ad610af8bd72962

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5700c7b74c37eb61946eb24041aa15992b6d5bdf6b47d07e2866a65a6efec9f4

**Comment by thnkgod4** [comment]
My Address: 0x641b654b8903bada337b3d7abf4533d6ebab0f49

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5afd7172c2615d4dc6eb2e7c23ae6081057d11412e9823c2c27884848f96d94b

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xb35919bea020a4eb44b50a48918e14a97af6cf60eb9d9f8b1322485c3308e836

**Comment by Nonandob** [comment]
My Address: 0xB68DdF19ECE588d402f80E0b21EE7d6b9251136D

Claim Reward:

I claimed 19.68 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xefbda6062b509e50977a10ff4d777d507ed05efbbd3711c8e82a2bc2d8ec8c7c

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x079275cbd9c17a00e0606870d6b22f5d609b76e7d2460a899a5eef190172a16d

**Comment by adaptecon** [comment]
My Address: 0x850bae06d8e56a5fd4117640c023f942697d771c

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe092654b9d768eafc9fdc9c69ebb7cc07ac036852155e40f186d201537d1b845

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc7002f12e26666dd50bb5ff13dd7de861af10513840116f4d1e38e70728f6262

**Comment by Alexcns** [comment]
My Address: 0xaEAC024c62FcaDDd3470E0ECea3C09C9154200Db

Claim Reward:

I claimed 19.95 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7c26e394e735b2855a5c2fcb22323f29ba51b59e668b37b1cd3f074a0ca0b0a0

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe0a3f4c7eb691514c689dc5663260d8b1491494a8da587fdcc81e0a8b3315d54

**Comment by murcomtel** [comment]
My Address: 0x40dbaae8374bb4361a61e5292922b051d45181c5

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x511f26aa0825ea12d5593c66a920bdd3b8eb5ed85a59a000e079d81a4fbc3025

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5824035d1053e57218762f08f3f708680eb9cb1751f233f8d58088ec3713eca4

**Comment by gsampathkumar** [comment]
My Address: 0xCdFC898128DBC380A60895c6E8C0975Dc07D07E0

Claim Reward:

I claimed 97.13 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe36159abef082daa7d862d385107bf43337faa98c927c1afd882ae47f65889cb

Restake: I restaked 97.13 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xbd25d127f48b76f0e838c3fc284b4583a2d9807954c1c72d5cf3d37f1fb19cb4

**Comment by SiChuanblue** [comment]
My Address: 0x50780E6aB93bbF35019D35E39956447Fc3018b12

Claim Reward:

I claimed 19.45 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x15c8c9a2372cb837f99135de1048f38b9b7c3e176278ecdbe84df609eedb6f07

Restake: I restaked 50 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xbf63874a756abb29006b18bbf642ae1c599a1907b0a7ea11911959a6312d5a9d

**Comment by sfoxdev** [comment]
My Address: 0x53f0Bf4e2029E7106d0699746c4da795e78070f9

Claim Reward:
I claimed 105.511733854337818671 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0x93d37e848f195b081eb10a9e24c31832a9c77363721e432cd44d5330a8977a1c

Restake: I restaked 20 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0xd120cf87e75320a43415d9c253e79a0968b6ebe516e2079550930638d13bb970

**Comment by maxfilppov** [comment]
My Address: 0xc01e78b56c02c075b51391c27a7b78f39ac3ae3e

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe9d6a6d2aa3cde97f9ebd47745d12e4bafd9877095564d0785af2e0fd6f442d8

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x02ca54cf8932852ca91edd8ae7505d04d824f7532acc14feebf617c5f881ff9a

**Comment by nikita-ul** [comment]
My address: 0xe648df7baea265dd051c2b3b2ac73def4fa054b1

Claim Reward:

I claimed 94.147589540343298888  Matic Tokens and here is the proof - 
https://goerli.etherscan.io/tx/0x5a9a46637d8bf716238e4ec4fd7875e29c2b87e9d44c44d4ca09dbfed52f9868

Restake: I restaked 90 Matic Tokens and here is the proof - 
https://goerli.etherscan.io/tx/0x922f7e7975f755315c204d5e47f8b609939a49e4e92806ee21b05aed26bcdfcb

**Comment by hunanzc** [comment]
My Address: 0x2314f1870f040983E64373BA3C33d025CdDe7BB6

Claim Reward:

I claimed 19.95 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xbbeac423d3cb9bd067ca3a2cee9155f9cd28904ec7a16837862440d7a3098392

Restake: I restaked 40 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xac2d23f5730009d626ca5234f2d2c40258abcb6bbf65bef21e3b421a83e7a387

**Comment by strubutas** [comment]
My Address: 0xF217022Cd526d33e7b8Eaf6825A359aD2140a247

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xfc0531be30574a114ced028b829bb645d50b767c60e91bd12389330b10639bc5

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc3d073bb65133c736b7a260b8bb45efaf81f4605e43741a5a60999048c8eb8fc

**Comment by alexgs273** [comment]
My Address: 0x207026cfbeb94a5f7810b150314db27951f66dbd

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x21353bbb6be04a17e72b3a87e356791cc1d8a86ff6e81afc53df0f69579d8639

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x942b9c733967fc819744b7481aa598ed15688f0a8bc72b4ceec0e7c09a21d73e

**Comment by saulina264** [comment]
My Address: 0x652b87123371114edc8a7b1ce5b3c05cf860fe38

Claim Reward:

I claimed 90.172363050392611294 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xf9ed6bc0059a75fd617003080375e1366a71a4436a8d2e01c7b73dbf63443035
Restake: I restaked 80 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x67944bfaf1304f05339403d1bfb473e8bd49d2916e1395f741648a3204b87ea4

**Comment by vapastukhov** [comment]
My Address: 0x08607b513090aa7f9f4614ae76c2d5d22609c7ee

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7789c78b28e1ecf13d003fdc6b4c1bfa4ec2c4e5c330755e7c5422a527926228

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x3cddc23478ee6a8bad67b95b443bfe25a5abbb4bc712ad2d4fa04b1f5ffe62bd

**Comment by gxhandsame** [comment]
My Address: 0xD90d3546609B776207262AEe5e51518f7fadE157

Claim Reward:

I claimed 25.65 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x396fd2e1778c2bab2e55e4f5beff6e067d8c1eacee4199fba9bf01871251500f

Restake: I restaked 20 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7e40ec8010a80a92b3589e840dc7b029a90afc42c181c0b8dedabc296e40a589

**Comment by AlexDCryptoC** [comment]
My Address: 0x3d9b28049256e96797c8fe73353b76434e57f7d2

Claim Reward:
I claimed 6.754364180827588069 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc439274973fb1c969be0790b976b243a3a50cfe7b06c68cc75090bf879a8857f

Restake: I restaked 6 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x8d189f4336357db1ae65d2cd3bbc69eba205509d1a84f5c96ec31c21743a4c33

**Comment by inundacion** [comment]
My Address: 0x300c7bbbd6a28b084526b4ebb7a810f51f85dfb4

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x00d86722ea1ab92d90a683b4a6e19692b8184c624cfa098e07dc41840bfad879

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x2efaee632aa1c92e28304203ec2fd60cc80b0ed26262896a654cd70cb9dfd457

**Comment by caligulastim** [comment]
My Address: 0xeb571ef6f80ae4fb2ffe4fb49419929587b8bc27

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7d5775350fc2f8d898361438c4699d2e39ff633b8e534c650601adcafde1ffb8

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5405d5226bf8f6370f25dbc2bfe6e9441daa1c83075c4c67aeac2bd8d388d80e

**Comment by svenski123** [comment]
My Address: 0x2E2de368D26A56445875D56D6Ad55aa5C896F112

Claim Reward:

I claimed 80.443090539252157113 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc828ba7a7236830e091abf2bd886fe1f0042cb527ad1fe8372d764957e181a57

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x3dee22686aefca75fa2f57797c6e6b76ac512b29bb2ea93baac97527caf71028

**Comment by epicrisetwins** [comment]
My Address: 0xe54254df5fd88b4d673fd9ec5e40ebccb2b51ed3

Claim Reward:

I claimed 241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x59c9f5678dcd7c86f5e9e538f986b4a3033828e65a59994ac0277ae3fa25f0c4

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xb9599474eac9c7c551cca27b512f70955a3a2f30293346fd1c169063aa365ac2

**Comment by UbikCapital** [comment]
My Address: 0xC869a1389cab3594175f7a017e4b932C9E982434
I claimed 6.470567366507101173  Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x3b177a69666b86d57929e19deee1caab526b0eb5f5f667aa97708113158bcd34

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x40c62a64e03ef2f63cb5c94a6ea757f131e8935c883f09dc146680e06446d886

**Comment by traylernemega** [comment]
My Address: 0xa722d5ee9da06740873f5aa8749e817558694394

Claim Reward:

I claimed 4.077907373292017876 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x39b217787a9fca8bd0fe5f06189b82ef3ecc4e6dcb23c956850bc93dfb3b5f55

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5aff65d9f4824a3dee0fdaefc0cb037dd2d3e7bb2a745aa7557c8965b32c046b

**Comment by Chainode** [comment]
My Address: 0x7Ae61c696696398FE100E0F813F96FFafE5Dad4d

Claim Reward: 
I claimed 7.317511432066390723 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x4029921787eba492b40affeb1d29395522e709a9e4f247611b19de4c39110df2

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xd14afaf66d75984a3e15535024239b89199f7c2737a700b586926be468987ef9

**Comment by oddinweb** [comment]
My Address: 0xf6537ff61fbd16d870753f846aeed0eb74975f98

Claim Reward:

I claimed 12.256293039530759241 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xe0ff7d6d7ae4b1a6e5dedf4644a46b889dde111e00d462830f7d277dad12d85f

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xed664127155b03848af65737227a91b94d30f145d201b2f15ea0ffd37d1a016b

**Comment by izotdm** [comment]
My Address: 0x5b6d16b1c9Af00686393bDc21e8d8Bd9a48E2630

Claim Reward:

I claimed 4.131227333055475985 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xb767abce52cd42425d015233d236f012382ddf51c8950e998ce2151ff49cb01b

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xa1182878563f231cae37a22b49fa6ffa86c212788e4082cb6db62d464c90b615

**Comment by r3dub** [comment]
My Address: 0x18E8c9201e89EaaF657Cb1912AD137436E8a03B1

Claim Reward:

I claimed 8.553574941083438672 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x794169b8c20e513f6ab0dd3960b1d66e1bf1ee1ef687ef3cca6d35043ce70f98

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xb2ad06a92a2c408bc8b40e511cfafd46c7bab07de74a6cd0970bb7f8829778a6

**Comment by temtitcvo** [comment]
My Address: 0x626512FB45a760B4d7cC75C5c5b77878F9291e2f

Claim Reward:

I claimed 9.532615554103627622 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x269814c3b0dc01d77d094c9afbf7fac08f00bfd94726baa40d7f3c3216b88982

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x2507ef9f64320ac23bee7eaf0f93e347e3619e49465360730ac1604809b04578

**Comment by mabalaru** [comment]
My Address: 0xB8C6E43f37E04A2411562a13c1C48B3ad5975cf4

Claim Reward:

I claimed 7.521359180600030918 Matic Tokens and here is the proof :  0xf18e95502618a70c6e0933a422a78928169a495efea7a7ebde605f12e01f7cf9

Restake: I restaked 10 Matic Tokens and here is the proof: 0x9dbb62407983cc932d81daf2c9d39d6ab962734e5bfdf52e4c30ddd627a5afc4

**Comment by stevegachau** [comment]
My Address: 0xd01ffAfa008Ad7753Cf00F6d77d65d8A3EBB15ac

Claim Reward:

I claimed 46.466435183011080894 Matic Tokens and here is the proof : https://goerli.etherscan.io/tx/0xf28af9f43068f4aaf9e8779436966f68a84a91567b0ee99a1991e0bd8e2ee854

Restake: I restaked 250 Matic Tokens and here is the proof: https://goerli.etherscan.io/tx/0xec29f8f0470e3ea03474ff4ab8af8eb1c9ab0b827e4dd38e0041b9157a332aff

**Comment by rewseRE** [comment]
My Address: 0x8C51296091C9C4F3bB2021516CD1A01f1C2c0F5a

Claim Reward:

I claimed 29.92877870962213338 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xaf62e1173cd8fb9010934b41997ecf3748c7dfbde5e333621f2e89b495c15aa1

Restake: I restaked 55 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x3a696a66b2b20dda5f0608648e27e326538a1b34a83994f0f7cb0272f2067583

**Comment by jericho-git** [comment]
My Address: 0xccA196b7E7De8e16A089b9B34be8CA83C26E807C

Claim Reward:

I claimed 57.242759707827645305 and here is the proof - https://goerli.etherscan.io/tx/0xfe7ae730fbae444218b8334d2419d4a062b01d84d29ba384a046d9cffd715a80

Restake: I restaked 74 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x31416221ccade255fdac2dd5a809fd39e9780801ac3bdd131030a18da2a5983f

**Comment by nshrd** [comment]
My Address: 0x0796E37e28356D3438b7428240B7B914DCAEde39

Claim Reward:

I claimed 10.720819593622508292 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0xd4200b4e0c62212db2c3da438ef174fe2c7960ae16e8d393db4a1e115077c164

Restake: I restaked 20 Matic Tokens and here is the proof -
https://goerli.etherscan.io/tx/0x2718325d60e98ef2690eef32c87eb76de287695aa337984e641f053d3638c354

**Comment by wjdfx** [comment]
My address: 0x9Beebb1230D10a4fD6D0b0BcdF3a68f0b0364F55

Claim Reward:

I claimed 41.010038168851391022 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x915be18a7f617a0297d37f6025ade299a68327b014999af2240c592a4dfe93a1

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x2518b5698cd1318a9df7bc229c60b7f6ad7a6e983f91040883a8d02cfaa521ed

**Comment by jetlag666** [comment]
My Address: 0x4Fd00E5d9C0d41615479B964D6E573B59554e9ec

Claim Reward:

I claimed 9 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x9fbce6aa17f7f0bd51421f66ee393d2f0b04e85faa521ab2b54f8c531af4423a

Restake: I restaked 50 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x5f515ffee656fceaab1aa2d4117862ac1a6cf2d40fe29249c755b593d2841408

**Comment by suddenrip** [comment]
My Address: 0x281c6C961e0E7DC3c4E2DaC4e33698FdAEF404E2

Claim Reward:

I claimed 115.045158980091226002 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0xc9e2c334d6cfb19a720bc38785e7c2100b21b5119b8db1410e3a29e80290e879

Restake: I restaked 120 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x8c69a46db58bb069071841e48a98ea746cc3db251a25a0741c008bbc727c043d

**Comment by andreisid** [comment]
My Address: 0x673447F1980bCb5C644379d7F1a6834C5Ec9c04e

Claim Reward:

I claimed 2.278107665485728341 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x2b94e63de910438ee55efc37c34d7cd1b7bbdc64e9ac116b10997317150ee770

Restake: I restaked 10 Matic Tokens and here is the proof - https://goerli.etherscan.io/tx/0x7ff02db47cc9b3a5c797e85b7301e3af3838e69d4c17cf9817b6ca8a3e2ba984

**Comment by delroybosco** [comment]
Closing this issue, we have already posted the winners list on the forum: https://forum.matic.network/t/mini-contest-day-1-claim-rewards-and-re-stake-winners/185
